Reduce scrolling for components on sensor list page
ska-sa/katgui pull request #596
Opened 2021-08-18 13:35 UTC by bxaia

This PR reduces scrolling for the components and proxies on the sensor list by increasing the number of columns from 2 to 4.

*Screenshots or code snippets (if appropriate):*
<img width="1672" alt="Screenshot 2021-08-18 at 15 23 28" src="https://user-images.githubusercontent.com/10397948/129907270-cc172a4e-6789-4a5f-be24-51c6bc7aaea6.png">

JIRA: [MT-2553](https://skaafrica.atlassian.net/browse/MT-2553)

2021-08-18 13:39 UTC, mmphego reviewed
Does it adapt to the number of proxies/components available(dynamic)? or is it statically set?

2021-08-18 13:49 UTC, amakhaba commented
> Does it adapt to the number of proxies/components available(dynamic)? or is it statically set?

Good Question mpho, I want to think it should since our boxes have different proxies and components

2021-08-18 13:53 UTC, ajoubertza commented
@bxaia Nice.  What does this look like on a smaller screen?  I have  2880 × 1800.  The screen shot is 3344 x 1714 pixels.

2021-08-18 14:06 UTC, ajoubertza commented
In PR description:
> columns from 2 to 4.

Screen shot shows 5 columns?

2021-08-19 06:52 UTC, bxaia commented
> Does it adapt to the number of proxies/components available(dynamic)? or is it statically set?

It is statically set.

2021-08-19 06:56 UTC, bxaia commented
> In PR description:
> 
> > columns from 2 to 4.
> 
> Screen shot shows 5 columns?

Sorry it was a typo on the PR description, I will test in depth with different screens and and also test with fewer proxies/components. It is also possible to give both proxies and components 50% height, but this was the initial implementation since there were more proxies than components

2021-08-19 09:57 UTC, ajoubertza commented
> It is also possible to give both proxies and components 50% height, but this was the initial implementation since there were more proxies than components

We can use a different ratio - it was just an example.

2021-08-23 09:14 UTC, bngcebetsha commented
# Work In Progress
#### On a big secondary screen I see
![onBigScreen](https://user-images.githubusercontent.com/20422017/130421909-b6499f96-bc8b-43ed-b432-b8c1d8a08fcd.png)

#### On the primary screen I see
<img width="1645" alt="onMainScreen" src="https://user-images.githubusercontent.com/20422017/130421923-02c7da2d-8c2e-48c3-bed5-849a2bdf6544.png">

Not sure if this can be made to look the same. Will spend some time checking

2021-08-23 13:03 UTC, ajoubertza commented
I've updated the description with the new layout from 48fea6e.

2021-08-23 13:09 UTC, ajoubertza approved these changes
LGTM

2021-08-23 13:09 UTC, ajoubertza commented on app/sensor-list/sensor-list.html
> +                    <div flex="25" ng-class="{'active-sensor-list-resource':vm.resourceSensorsBeingDisplayed === resource.name}"
For those wondering, the `flex` parameter is a percentage.  With 2 columns, each uses 50%.  With 4 columns, each use 25%.

2021-08-23 13:09 UTC, ajoubertza commented on app/sensor-list/sensor-list.html
> +        <div layout="column" style="width: 432px">
This was updated by inspection.  With two columns, each label had 106 pixels.  `2*106 + 8 = 220`.  With four columns, we use `2*106 + 8 = 432`.

2021-08-23 13:56 UTC, amakhaba approved these changes
LGTM

2021-08-24 07:32 UTC, ajoubertza commented
It seems like the problem with the latest dist files (and local via gulp webserver), is related to a change in the [`$mdtoast` API](https://material.angularjs.org/1.2.3/api/service/$mdToast#mdtoast-simple).

Error:
![image](https://user-images.githubusercontent.com/20420754/130573895-a856ff3d-b97e-419c-b72f-b3cd0eeb1295.png)

Fix:
```diff
diff --git a/app/services/notify-service.js b/app/services/notify-service.js
index 2658071..81f54a8 100644
--- a/app/services/notify-service.js
+++ b/app/services/notify-service.js
@@ -21,7 +21,7 @@
             if (!api.currentToast) {
                 api.currentToast = $mdToast.simple();
                 api.currentToast
-                    .content(message)
+                    .textContent(message)
                     .hideDelay(false) // never hide automatically
                     .position(api.toastPosition);
                 $mdToast.show(api.currentToast);
```

See all the breaking changes for 1.2.0 here:  https://github.com/angular/material/blob/v1.2.2/CHANGELOG.md#breaking-changes.  E.g., we should fix `$mdDialog`, which has a similar change.

2021-08-24 07:33 UTC, ajoubertza requested changes
Need to fix the `content` to `textContent` issues

2021-08-24 07:58 UTC, ajoubertza commented
It looks like the previous working builds were made with version angular-material 1.1.6.

![image](https://user-images.githubusercontent.com/20420754/130579187-e2ff5326-f34f-4492-a629-fab26bd7a0b3.png)

2021-08-24 10:40 UTC, ajoubertza commented
> It looks like the previous working builds were made with version angular-material 1.1.6. (This differs from the package.json promise of 1.2.2)

After some unsuccessful testing, with newer packages, we've decided to revert to the older packages (angular 1.6.10, angular-material 1.1.6).

2021-08-24 11:49 UTC, ajoubertza approved these changes
LGTM

2021-08-24 11:54 UTC, merged