Set default centre frequency in narrowband mode
ska-sa/katgui pull request #602
Opened 2021-08-31 10:42 UTC by bngcebetsha

We set and display the default narrowband center frequency on L-band. In conjunction with changes in katconfig

JIRA: [MT-2566](https://skaafrica.atlassian.net/browse/MT-2566)

2021-08-31 12:22 UTC, lanceWilliams commented on app/scheduler/scheduler-home.js
> +            vm.updateFrequency(label, frequency, nb_frequency);
Is this the only place that the 'updateFrequency' function is used?

2021-09-01 14:09 UTC, ajoubertza requested changes
Still needs to be updated to use new key-value definition in katconfig:  `narrowband_defaults`

2021-09-02 06:59 UTC, ajoubertza commented
Has this been tested for other bands?  It doesn't look like it would work - we aren't storing the narrowband defaults for each band.

2021-09-03 11:00 UTC, ajoubertza requested changes
The different bands are handled better now, but there is a problem with edge cases.

2021-09-03 11:00 UTC, ajoubertza commented on app/scheduler/scheduler-home.js
> +                vm.setNarrowFrequency(defaultNarrowFreq, i);
Is this loop correct?  The keys for `vm.defaultNarrowBandFreqMap` should be the band letters:  `l`, `s`, `u`, `x`.  That means `i` goes from 0 to 4.  That happens to equal 5 items, which is the number of narrowband instruments we allow.  However the number of bands and number of narrowband instruments are not related.  That is why we used to use the `ObsSchedService.numberOfNarrowBands` value.

Also, the keys in a single band's dict, i.e., in `vm.defaultNarrowBandFreqMap[vm.subarray.band]` would be `nb1`, `nb2`, ..., `nb5` (from `labelledNarrowbandDefaults`).  That means we skip the last one, and try look up a missing item `nb0`.

2021-09-03 11:54 UTC, amakhaba commented on app/scheduler/scheduler-home.js
> +                vm.setNarrowFrequency(defaultNarrowFreq, i);
This is correct, previously when we were directly obtaining the narroband_freq defaults from the dictionary `defaultNarrowBandFreqMap` that's why we were using `=Object.keys(vm.defaultNarrowBandFreqMap).length`. What you are mentioning is a small detail we missed when handling the new implementation. I will address it.

2021-09-03 13:04 UTC, ajoubertza commented on app/scheduler/scheduler-home.js
> +            for (var i=0; i<=i<=ObsSchedService.numberOfNarrowBands; i++){
Two questions:
- Is `i<=i<=ObsSchedService.numberOfNarrowBands` valid JavaScript syntax?
- Why do we start from 0 here, but start from 1 on line 166?

2021-09-03 13:18 UTC, bngcebetsha commented on app/scheduler/scheduler-home.js
> +            for (var i=0; i<=i<=ObsSchedService.numberOfNarrowBands; i++){
big mistake, will fix this now

2021-09-03 13:37 UTC, ajoubertza commented
@bngcebetsha Has the latest code, @bngcebetsha, 4e39b6a, been testing for different bands and confirmed to be working as expected?

2021-09-03 13:46 UTC, bngcebetsha commented
> @bngcebetsha Has the latest code, [4e39b6a](https://github.com/ska-sa/katgui/commit/4e39b6a30e8bbe33ecca9bd334aa3eb1e53a1f66), been testing for different bands and confirmed to be working as expected?

yes

2021-09-03 13:57 UTC, ajoubertza approved these changes

2021-09-03 14:38 UTC, merged