Add CI stage for katgui to auto build dist files after a PR has been approved and ready for merge
ska-sa/katgui pull request #627
Opened 2022-05-20 11:18 UTC by amakhaba

The katgui Jenkins job already builds the dist files as a check.  However, developers must still manually build, commit and push the dist files from their local development environment to create a new release.  This is tedious and error-prone.  

This PR adds a stage in the Jenkins file to automatically build, commit and push dist files when a Pull request has been approved and ready for merge.

![distfilescommit](https://user-images.githubusercontent.com/31302703/169762824-cc737b2e-fb1e-47ce-ae41-b268c32071fe.png)

JIRA: [1843](https://skaafrica.atlassian.net/browse/1843)

2022-05-20 11:30 UTC, mmphego approved these changes

2022-05-23 08:36 UTC, bngcebetsha reviewed
I suppose the dist files in this PR are outputs of this functionality in action

2022-05-23 08:36 UTC, bngcebetsha commented on Jenkinsfile
> +
do we need this extra empty line?

2022-05-23 08:36 UTC, bngcebetsha commented on Makefile
> +	git push "https://$(GITHUB_USER):$(GITHUB_TOKEN)@github.com/ska-sa/katgui"
the `GITHUB_USER` and the `automated_katgui_user` will be the same? not sure if them being different will be a major issue...I imagine not

2022-05-23 08:56 UTC, amakhaba commented on Makefile
> +	git push "https://$(GITHUB_USER):$(GITHUB_TOKEN)@github.com/ska-sa/katgui"
Nope they are not the same, we added the `automated_kagui_user` as the committer just to improve readability and awareness to the next person that sees that commit, and again no we do not anticipate an issue later as that `automated_katgui_user` is not a recognised user in git

2022-05-23 09:58 UTC, mmphego requested changes

2022-05-23 09:58 UTC, mmphego commented on Jenkinsfile
> +                    env.PR_APPROVED == 'approved' && env.COMMIT_AUTHORED == 'un_committed'
This logic did not work as expected @amakhaba. Please look into it and refine it

2022-05-23 09:58 UTC, mmphego commented on Jenkinsfile
> +
Nope! @amakhaba please fix

2022-05-23 09:58 UTC, mmphego commented on Jenkinsfile
> +        get_commit_message(pr_number)
@amakhaba please look into this logic, Ideally, we want to ensure that the PR is approved before building the dist files and only commit if previously uncommitted. My logic was a bit skewed this morning,.

2022-05-24 05:03 UTC, mmphego approved these changes
Looks good to me.

2022-05-24 07:27 UTC, lanceWilliams commented on Jenkinsfile
> +        stage('Install Dependencies') {
Not sure if this is just a renaming of a different stage but is the 'Unit Tests' aspect of that stage not required anymore?

2022-05-24 07:32 UTC, tockards commented on Jenkinsfile
> +                        file: 'check_pr_state.py',
I take it there is some specific reason to why we are doing it this way as opposed to pulling the code from an exisiting repo/location, If so please explain.

It just seems very clunky to manage a python code that is in jenkins file.

2022-05-24 07:50 UTC, mmphego approved these changes

2022-05-24 07:50 UTC, mmphego commented on Jenkinsfile
> +        KATCONFIGUSER_LOGIN = credentials('katconfiguser-credentials')
@amakhaba Please update the cam secret docs with the credentials and instructions on how to recreate the token.

2022-05-24 07:51 UTC, mmphego commented on Jenkinsfile
> +        stage('Install Dependencies') {
We do not have any unittests for katgui and this moment, hence we opted to remove it from the stage name.

2022-05-24 07:52 UTC, mmphego commented on Jenkinsfile
> +                        file: 'check_pr_state.py',
Yeah true, we initially had it as a script but then decided to place it as part of the Jenkinsfile to avoid having multiple files/script on the root directory. I suppose we can make a separate directory for misc files and run the script from there.

2022-05-24 08:20 UTC, amakhaba commented on Jenkinsfile
> +        KATCONFIGUSER_LOGIN = credentials('katconfiguser-credentials')
I have done that under the katconfiguser section, I also have a calender invite please ping me if you need to be added to it.

2022-05-24 09:06 UTC, bngcebetsha approved these changes
LGTM

2022-05-24 10:08 UTC, mmphego requested changes
Run isort, flake8 and black, then fix up the errors.

2022-05-24 10:08 UTC, mmphego commented on misc/check_pr_state.py
> +import json
Overall, great implementation. You can benefit a lot from using these tools for formatting and error-checking your code in the future.

- [https://github.com/psf/black](https://github.com/psf/black)
- [https://github.com/PyCQA/isort](https://github.com/PyCQA/isort)
- [https://flake8.pycqa.org/en/latest/](https://flake8.pycqa.org/en/latest/)

2022-05-24 10:54 UTC, mmphego approved these changes

2022-05-24 11:14 UTC, merged